<?php

function gnm2018_provenienz_preprocess_field(&$variables, $hook) {
#  dpm(serialize($variable), "yay!");

  $element = $variables['element'];

  global $wisski_seen_that;

  // objektkategorie rewrite
  if($element['#field_name'] == 'f1621dd2af001f2f8b9e61b67040bbad') {
#    $variables['element']['#items'][0]['value'] = "Hallo welt!";
#    $value = &$variables['element']['#items'][0];
#    $value->setValue("Hallo welt!");
#    $variables['element']['#items'][0]->setValue("Hallo Welt!");
    $old = $variables['items'][0]['content']['#context']['value'];

    if(strpos($old, 'A:') !== FALSE)
      $variables['items'][0]['content']['#context']['value'] = 'Die Provenienz für den Zeitraum 1933 bis 1945 ist rekonstruierbar und unbedenklich.';
    else if(strpos($old, 'B:') !== FALSE)
      $variables['items'][0]['content']['#context']['value'] = 'Die Provenienz für den Zeitraum 1933 bis 1945 konnte nicht eindeutig geklärt werden.';
    else if(strpos($old, 'C:') !== FALSE)
      $variables['items'][0]['content']['#context']['value'] = 'Die Provenienz für den Zeitraum 1933 bis 1945 ist bedenklich, es liegen Verdachtsmomente vor.';
    else if(strpos($old, 'D:') !== FALSE)
      $variables = array();
#      $variables['element']['#field_type'] = "hidden";
#      unset($variables['items']);

#    dpm(serialize($variables), "saas");

#    $variables['items'][0]['content']['#context']['value'] = "nasenbaer";
#    dpm(serialize($variables['items'][0]['content']['#context']['value']), "null");
  } else if($element['#field_name'] == 'be1f6078d08aa778191c57207f1d7f82') { // rewrite fuer vermerk am objekt
#    $variables['items'][0]['content']['#plain_text'] = 'sdafjksdflhkjfdsfdslkjsdflkjdfslkjsdf';
#    $variables['element']['#title'] = "Objektautopsie"; 
    $variables['label'] = "Objektuntersuchung";
#    dpm(serialize($variables), "var");
    foreach($variables['items'] as $key => $value) {
      $old = $variables['items'][$key]['content']['#plain_text'];
#    dpm(serialize($variables['items'][$key]), "hui!");

      if(strpos($old, 'Objektautopsie: nicht erfolgt') !== FALSE) {
        if(strpos($old, 'nicht erfolgt, da Verlust lt. Inv.buch') || strpos($old, 'nicht erfolgt, da Verlust') || strpos($old, 'nicht erfolgt, da Objekt restituiert und abgegeben')) {
          $variables = array();
        } else {
          $variables['items'][$key]['content']['#plain_text'] = 'nicht erfolgt';
        }
      } else if(strpos($old, 'Objektautopsie:') !== FALSE) {
#      dpm(strpos($old, 'Objektautopsie:'), "yay!");
#      dpm(strlen('Objektautopsie:'), "cdd");
        $variables['items'][$key]['content']['#plain_text'] = trim(substr($old, (strlen('Objektautopsie:'))));
#      dpm($variables['items'][0]['content']['#plain_text'], "asdsdsd"); 
      } else {
        unset($variables['items'][$key]);
      }
    }
  } else if($element['#field_name'] == 'f5667493aae42a8372c59662de581fe8') {
    foreach($variables['items'] as $key => $value) {
      $old = $variables['items'][$key]['content']['#text'];
      $variables['items'][$key]['content']['#text'] = preg_replace('/<p><a href="#_ftn." title="">\[.\]<\/a><\/p>/', "", $old); 
      $variables['items'][$key]['content']['#text'] = preg_replace('/<p><strong>\&nbsp;<\/strong><\/p>/', "", $variables['items'][$key]['content']['#text']);
    }
  } else if($element['#field_name'] == 'f97855bad9c02a2b01ec1db619799615') { // rewrite for perma-link
    foreach($variables['items'] as $key => $value) {
#      dpm($variables['items'][$key]['content']['#url']->fromUserInput("/wisski/test"), "val");
      $variables['items'][$key]['content']['#url'] = $value['content']['#url']->fromUri(str_replace("https://provenienz.gnm.de/objekt/", "https://provenienz.gnm.de/wisski/get?uri=https://provenienz.gnm.de/objekt/", $value['content']['#url']->getUri())); #preg_replace('/<a href="https:\/\/provenienz\.gnm\.de\/objekt\/(.+)">(.+)<\/a>/', '<a href="https:\/\/provenienz\.gnm\.de\/wisski\/get?uri=https:\/\/provenienz\.gnm\.de\/objekt\/\1">\2<\/a>', $old);
    }
  } else if($element['#field_name'] == 'fb98fca58872705283e9ea64a8903444') { // rewrite for perma-link
    foreach($variables['items'] as $key => $value) {
#      dpm($variables['items'][$key]['content']['#url']->fromUserInput("/wisski/test"), "val");
      $variables['items'][$key]['content']['#url'] = $value['content']['#url']->fromUri(str_replace("https://provenienz.gnm.de/person/", "https://provenienz.gnm.de/wisski/get?uri=https://provenienz.gnm.de/person/", $value['content']['#url']->getUri())); #preg_replace('/<a href="https:\/\/provenienz\.gnm\.de\/objekt\/(.+)">(.+)<\/a>/', '<a href="https:\/\/provenienz\.gnm\.de\/wisski\/get?uri=https:\/\/provenienz\.gnm\.de\/objekt\/\1">\2<\/a>', $old);
    }
  } else if($element['#field_name'] == 'faaf9e9e6da7b6930ae0c12ef8a3866c') { // rewrite for perma-link
    foreach($variables['items'] as $key => $value) {
#      dpm($variables['items'][$key]['content']['#url']->fromUserInput("/wisski/test"), "val");
#      dpm($variables['items'][$key]['content']['#url'], "dp");
#      $variables['items'][$key]['content']['#url'] = $value['content']['#url']->fromUri(str_replace("https://provenienz.gnm.de/institution/", "https://provenienz.gnm.de/wisski/get?uri=https://provenienz.gnm.de/institution/", $value['content']['#url']->getUri())); 
    }
  }

  if($element['#field_name'] == 'f32b7f7ce4b6486c5de3a12d7b128233' || $element['#field_name'] == 'f32374a8de78d1e2495aeb8b16fda8c9' || $element['#field_name'] == 'f5d47d98cf1edce42f376147f25a0c6b' || $element['#field_name'] == 'f67586fdea4e4ca5d39517eaf189181d') {
    // if any of these is set already in some other field, reset it...
    foreach($variables['items'] as $key => $value) {

      if(isset($variables['items'][$key]['content']['#url'])) {
        $url = $variables['items'][$key]['content']['#url'];
        $route_para = $url->getRouteParameters();

        if(isset($route_para['wisski_individual'])) {
          $id = $route_para['wisski_individual'];
          if(isset($wisski_seen_that[$id])) {
            $variables = array();
          } else {
            $wisski_seen_that[$route_para['wisski_individual']] = TRUE;
          }
        }
      }
    }
  }

}



/*
function halfpastthreegrain_theme_suggestions_block_alter(array &$suggestions, array $variables) {
    // Block suggestions for custom block bundles.
    if (isset($variables['elements']['content']['#block_content'])) {
        array_splice($suggestions, 1, 0, 'block__bundle__' . $variables['elements']['content']['#block_content']->bundle());
    }
}
*/

/* must be person or institution in this case! */
/*
function gnm2018_provenienz_preprocess_layout__onecol__990px__nosidebar(&$variables) {
  dpm(serialize($variables["content"]["#wisski_individual"]->get("f32b7f7ce4b6486c5de3a12d7b128233")->getValue()), "var1");
  dpm(serialize($variables["content"]["#wisski_individual"]->get("f32374a8de78d1e2495aeb8b16fda8c9")->getValue()), "var2");
  dpm(serialize($variables["content"]["#wisski_individual"]->get("f5d47d98cf1edce42f376147f25a0c6b")->getValue()), "var3");
  dpm(serialize($variables["content"]["#wisski_individual"]->get("f67586fdea4e4ca5d39517eaf189181d")->getValue()), "var4");

  $variables["content"]["#wisski_individual"]->set("f32374a8de78d1e2495aeb8b16fda8c9", array());

  foreach($variables as $key => $variable) 
    dpm($key);
}
*/
/*
function gnm2018_provenienz_preprocess_page(&$variables) {
  dpm("yay!!!!!!!");
}

function gnm2018_provenienz_entity_view_alter(array &$build, Drupal\Core\Entity\EntityInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display) {
  dpm("yay!!");
}
*/
function gnm2018_provenienz_preprocess_breadcrumb(&$variables) {

  // hide "navigate"
  if(isset($variables['breadcrumb']) && isset ($variables['breadcrumb'][1]) && isset($variables['breadcrumb'][1]['url']) && $variables['breadcrumb'][1]['url'] == "/wisski/navigate")
    unset($variables['breadcrumb'][1]);
}
